#!/bin/bash
# servers are the piece of software generating and serving HTML pages

sudo apt update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
