#!/usr/bin/env bash
# servers are the piece of software generating and serving HTML pages

sudo apt update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

sudo sed -i "/'server_name _;'/a \
location '/redirect_me' {\
return 301 'https://www.youtube.com/watch?v=QH2-TGUlwu4;'\
}" /etc/nginx/sites-available/default

service nginx restart
