#!/usr/bin/env bash
# servers are the piece of software generating and serving HTML pages

sudo apt update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

printf "Ceci n'est pas une page\n" > /var/www/html/error_404.html

sed -i '/server_name _;/a\
error_page 404 /error_404.html;\
location = /error_404.html {\
\	 internal;\
}' /etc/nginx/sites-available/default

sed -i '/listen 80 default_server;/a\
\    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
