#!/usr/bin/env bash
# a script Install and configure HAproxy on your lb-01 server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update the System
sudo apt-get -y update
apt-get -y install haproxy=1.8.\*

# Firewall Rules
sudo ufw allow 80

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo bash -c 'cat >> /etc/haproxy/haproxy.cfg <<EOL


frontend http_front
	 bind *:80
	 default_backend main_backend

backend main_backend
	balance roundrobin
	server web-01 52.201.211.145:80 check
	server web-02 54.209.162.93:80 check
EOL'

# Start and Enable HAProxy
sudo systemctl start haproxy
sudo systemctl enable haproxy
