#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


_term() {
    rm /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap "echo 'I hate the kill command' && _term" SIGTERM
    trap "echo 'Y U no love me?!'" SIGINT
    trap "_term" SIGQUIT
done
