#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' ~/hosts.new
sed -i '$ a\8.8.8.8 facebook.com' ~/hosts.new
cp ~/hosts.new /etc/hosts
