#!/usr/bin/env bash
#to connect to your server using the private key ~/.ssh/school
#Only use ssh single-character flags
#You cannot use -l
#You do not need to handle the case of a private key protected by a passphrase

ssh -i ~/.ssh/school ubuntu@52.201.211.145
